name: lfric_ana
channels:
  - conda-forge
dependencies:
  - python =3.11

  - setuptools >=40.8.0

  - cartopy >=0.20
  - cf-units >=3
  - cftime >=1.5
  - dask >=2
  - matplotlib >=3.5
  - netcdf4
  - numpy
  - python-xxhash
  - scipy

  # - aeolus
  - esmpy >=7.0
  - flake8
  - graphviz
  - imageio-ffmpeg
  - ipykernel
  - ipython
  - ipywidgets
  - iris >=3.4
  - iris-esmf-regrid >=0.5
  - mo_pack
  - pandas
  - pip
  - python-stratify
  - tqdm

# Dev dependencies
  - f90nml
  - cached-property
  - latlon23
  - pip:
    - git+https://github.com/exoclim/aeolus
    - git+https://github.com/dennissergeev/pouch
