name: lfric_ana
channels:
- conda-forge
dependencies:
  - python =3.8

  - setuptools >=40.8.0

  - cartopy >=0.20
  - cf-units >=3
  - cftime >=1.5
  - dask >=2
  - matplotlib >=3.5
  - netcdf4
  - numpy >=1.14
  - python-xxhash
  - scipy

  - aeolus
  - esmpy >=7.0
  - flake8
  - graphviz
  - ipykernel
  - ipywidgets
  - iris >= 3.2.1
  - iris-esmf-regrid
  - mo_pack
  - nc-time-axis >=1.3
  - pandas
  - pip
  - python-stratify
  - tqdm

# Dev dependencies
  - pip:
#    - git+https://github.com/scitools-incubator/iris-esmf-regrid@unstructured_scheme
